config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :accounts, controllers: { registrations: 'registrations' }
  devise_scope :account do
    get '/p/:referrer_code', to: 'registrations#promolink', as: 'promolink'
    match '/auth/:provider/callback', to: 'registrations#omniauth', via: [:get, :post]
    get '/auth/failure', to: redirect('/')
  end

  # Panda Routes
  scope default_format: :json do
    post '/panda/authorize_upload', to: 'panda#authorize_upload'
    post '/panda/notifications', to: 'panda#notifications'
  end

  resources :videos do
    get :preview, on: :member
    put :refresh, on: :member
    get :download, on: :member
    get :selection, on: :collection
  end

  resources :messages do
    member do
      put :deliver
      put :clone
      get :preview
      get :statistics
    end
    
    collection do
      get :contacts
      get :statistics
      put :destroy_multiple
      put :restore_multiple
      put :really_destroy_multiple
    end
  end

  resources :templates, only: [:index, :show] do
    member do
      get :preview
      delete :remove
    end
    collection do
      get :selection
      get :available
    end
  end

  resources :products, only: [:index, :show] do
    put :add_to_user, on: :member
  end

  resources :orders, only: [:index, :new, :create]

  resources :pages, only:[] do
    get :termsofuse, on: :collection
    get :imprint, on: :collection
    get :contact, on: :collection 
  end

  resources :playlists do
    put :add_video, on: :member
    put :remove_video, on: :member
    get :selection, on: :collection
  end

  get '/record', to: 'video_recorder#record'
  get '/avc_settings', to: 'video_recorder#avc_settings'
  post '/jpg_encoder_download', to: 'video_recorder#jpg_encoder_download'

  namespace :admin do
    resources :videos do
      get :preview, on: :member
      put :refresh, on: :member
    end

    resources :templates
    resources :categories
    resources :settings

    resources :products do
      put :add_category, on: :member
      put :remove_category, on: :member
    end

    resources :packages do
      get :manage_templates, on: :member
      put :add_template, on: :member
      put :remove_template, on: :member
    end

    root 'templates#index'
  end

  root 'videos#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
  include TokenGenerator
  acts_as_paranoid

  belongs_to :account, counter_cache: true
  belongs_to :video
  belongs_to :template
  belongs_to :playlist

  has_many :access_logs, -> { order "accessed_at desc" }, class_name: 'MessageAccessLog'
  scope :by_token, ->(token) { where(token: token) }
  scope :by_status, ->(status) { where(status: status) }
  scope :delayed_drafts, ->{ where("send_at is not null").where(status: 'delayed', email_type: 1).order('send_at desc') }

  validates_presence_of :template
  validates_length_of :text, maximum: 2048
  validates_length_of :subject, maximum: 255

  validate :validate_emails
  validate :validate_video_playlist
  validate :validate_template
  validate :validate_video
  validate :validate_delayed_email

  before_save :set_video_playlist

  STATUSES = %w(draft sent delayed)
  PLAY_TYPES = %w(video list)
  EMAIL_TYPES = %w(normal delayed)

  Message::STATUSES.each do |status|
    define_method("#{status}?") do
      self.status == status
    end
  end

  def clone_message
    message = self.dup
    message.token = nil
    message.created_at = message.updated_at = Time.now
    message.send_at = nil
    message.status = 'draft'
    message.save

    message
  end

  def emails_to_a
    self.emails.gsub(/\s+/, '').split(',')
  end

  def validate_emails
    errors.add(:emails, 'cannot be blank.') if self.emails.blank? || self.emails_to_a.count == 0
  end

  def validate_delayed_email
    if self.delayed_email? && self.draft? && (Time.now > self.send_at)
      errors.add(:send_at, 'cannot be before than now.')
    end
  end

  def validate_video_playlist
    if self.video_id.blank? and self.playlist_id.blank?
      errors.add(:play, 'video or playlist cannot be blank.')
    else
      errors.add(:playlist, "couldn't be blank") if self.play == 'list' && self.playlist_id == nil
      errors.add(:video, "couldn't be blank") if self.play != 'list' && self.video_id == nil
    end
  end

  def validate_template
    if template && account
      unless account.can_use_template?(template, persisted?)
        errors.add(:template, "can't be used, upgrade your plan")
      end
    end
  end

  def validate_video
    if video && account
      unless account.can_use_video_duration_of?(video.duration)
        errors.add(:video, "can't be used, your current plan has video duration limit, upgrade your plan")
      end
    end
  end

  def delayed_email?
    self.email_type == 1
  end

  def deliver
    if self.delayed_email?
      deliver_later
    else
      deliver_now
    end
  end

  def deliver_now
    self.emails_to_a.each do |email|
      VideoMailer.template_email(self, email).deliver
    end
    self.status = 'sent'
    self.send_at = Time.now
    self.save
  end

  def deliver_later
    self.status = 'delayed'
    self.save
  end

  def self.deliver_delayed
    Message.delayed_drafts.where('send_at < ?', Time.now).each do |message|
      message.deliver_now
    end
  end

  def read_by!(email)
    last_accessed_at = self.access_logs.by_email(email).first.try(:accessed_at) || 1.year.ago
    if last_accessed_at < 5.minutes.ago
      self.access_logs.create(email: email, accessed_at: Time.now)
    end
  end

  def read_by?(email)
    !self.access_logs.where(email: email).blank?
  end
  
  def read_any?
    self.access_logs.count > 0
  end

  private

  def set_video_playlist
    if self.play == 'list'
      self.video_id = nil
    else
      self.playlist_id = nil
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :set_message, only: [:deliver, :edit, :update, :destroy, :show, :clone, :preview, :statistics]

  before_filter only: [:new, :create, :clone] do
    unless current_account.can_create_message?
      redirect_to messages_path, notice: 'Upgrade your plan to create more videomails'
      false
    end
  end

  def index
    status = params[:status]
    status ||= 'all'
    set_tab status
    @messages = current_account.messages_in_status(params[:status]).order('updated_at desc').page(params[:page])

    unless params[:statistics].blank?
      set_tab :statistics
      render :index_with_statistics
    end
  end

  def show
    @video = @message.video
    @playlist = @message.playlist
    @template = @message.template
    @back = true

    if !@video.blank?
      render 'videos/show', layout: 'email'
    elsif !@playlist.blank?
      render 'playlists/show', layout: 'email'
    end
  end

  def new
    @message = current_account.messages.build
    @message.template = Template.default_templates.first

    if params[:video_id].present?
      @message.video = current_account.videos.encoded.find_by_id(params[:video_id])
      @message.play = 'video'
    elsif params[:playlist_id].present?
      @message.playlist = current_account.playlists.find_by_id(params[:playlist_id])
      @message.play = 'list'
    end

    load_data
  end

  def create
    @message = current_account.messages.build(message_params)
    if @message.save
      flash[:success] = 'Message successfully created'

      if params[:commit] == 'Send'
        @message.deliver
        if !@message.delayed_email?
          flash[:success] = 'Message successfully sent'
        else
          flash[:success] = "Message will send at #{@message.send_at}"
        end
      end

      redirect_to edit_message_path(@message)
    else
      load_data

      flash.now[:danger] = @message.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    load_data
  end

  def update
    if @message.update_attributes(message_params)
      flash[:success] = 'Message updated successfully'
      if params[:commit] == 'Send'
        @message.deliver
        if !@message.delayed_email?
          flash[:success] = 'Message sent successfully'
        else
          flash[:success] = "Message will be sent at #{@message.send_at}"
        end
      end
      redirect_to edit_message_path(@message)
    else
      flash[:danger] = @message.errors.full_messages.to_sentence
      redirect_to edit_message_path(@message)
    end
  end

  def destroy
    @message.destroy
    redirect_to messages_path
  end

  def destroy_multiple
    params[:messages].each do |message_id|
      current_account.messages.find(message_id).destroy
    end

    flash[:success] = 'Messages deleted successfully'
    redirect_to messages_path
  end

  def restore_multiple
    params[:messages].each do |message_id|
      current_account.messages.with_deleted.find(message_id).restore
    end

    flash[:success] = 'Messages deleted successfully'
    redirect_to messages_path
  end

  def really_destroy_multiple
    params[:messages].each do |message_id|
      current_account.messages.with_deleted.find(message_id).really_destroy!
    end

    flash[:success] = 'Messages deleted permanently'
    redirect_to messages_path(status: 'trash')
  end
  
  def preview
    @video = @message.video
    @template = @message.template
    @playlist = @message.playlist
    @back = true
    render layout:'layouts/email'
  end

  def statistics
    render layout: false
  end

  def deliver
    if @message.valid?
      @message.deliver_now
      flash[:success] = 'Message successfully sent.'
      redirect_to messages_path
    else
      flash[:danger] = "Sorry, couldn't send email now"
      redirect_to edit_message_path(@message)
    end
  end

  def clone
    @message = @message.clone_message

    flash[:success] = 'Message successfully cloned'
    redirect_to edit_message_path(@message)
  end

  #TODO
  def contacts
    head :ok
  end

  private

  def load_data
    @templates = current_account.templates
    @videos = current_account.videos.encoded
    @playlists = current_account.playlists
  end

  def message_params
    attrs = [:subject, :text, :template_id, :message_id, :account_id, :video_id, :send_at, :email_type, :emails, :downloadable]

    if current_account.can_use_video_playlist?
      attrs += [:playlist_id, :play]
    end

    params.require(:message).permit(*attrs)
  end

  def set_message
    @message = current_account.messages.find(params[:id])
  end
end

app/views/messages/_form.html.haml
- @message.play = 'video' if @message.play.blank?

= bootstrap_form_for(@message, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-10') do |f|
  = f.text_field :emails, class: 'form-control typeahead', placeholder: 'Emails separeted by ,'
  - if @message.video && @message.subject.blank?
    = f.text_field :subject, class: 'form-control', value: @message.video.title
  - else
    = f.text_field :subject, class: 'form-control', placeholder: 'Give a Title'
  = f.form_group do
    = f.bootsy_area :text, class: 'form-control', rows: 6, placeholder: 'Write your message'
  = f.form_group do
    .input-group
      .input-group-btn
        = link_to selection_templates_path, class: 'btn btn-default dropdown-toggle', "data-target" => "#modal-templates", "data-toggle" => "modal" do
          %span.caret

        %input.form-control.sample-template-text{:type => 'text', :value => f.object.try(:template).try(:title), :placeholder => 'Please choose a template', style: 'padding-left: 40px;'}
        = f.hidden_field :template_id

  - if current_account.can_use_video_playlist?
    = f.form_group :play, label: { text: 'Play' } do
      = f.radio_button :play, 'video', label: 'Single video', inline: true
      = f.radio_button :play, 'list', label: 'Playlist', inline: true

    = f.form_group class: 'playlists-group', style: 'display: none' do
      .input-group
        .input-group-btn
          = link_to selection_playlists_path, class: 'btn btn-default dropdown-toggle', "data-target" => "#modal-playlists", "data-toggle" => "modal" do
            %span.caret

          %input.form-control.sample-playlist-text{:type => 'text', :value => f.object.try(:playlist).try(:title), :placeholder => 'Please choose a playlist', style: 'padding-left: 40px;'}
          = f.hidden_field :playlist_id

  = f.form_group class: 'videos-group', style: 'display: none' do
    .input-group
      .input-group-btn
        = link_to selection_videos_path, class: 'btn btn-default dropdown-toggle', "data-target" => "#modal-videos", "data-toggle" => "modal" do
          %span.caret

        %input.form-control.sample-video-text{:type => 'text', :value => f.object.try(:video).try(:title), :placeholder => 'Please choose a video', style: 'padding-left: 40px;'}
        = f.hidden_field :video_id

  = f.form_group do
    = f.check_box :downloadable, hide_label: true do
      Allow recipient to download?

  = f.form_group do
    = f.check_box :email_type, hide_label: true do
      Send at scheduled time?
  #send_at
    = f.datetime_select :send_at, disabled: !@message.draft?, help: current_time_zone
  = f.form_group do
    - if @message.new_record? or @message.draft?
      = f.submit 'Save', class: 'btn btn-primary'
      = f.submit 'Send', class: 'btn btn-info'
    %br

#modal-templates.modal.fade{:role => "dialog"}
  .modal-dialog.modal-lg
    .modal-content

#modal-playlists.modal.fade{:role => "dialog"}
  .modal-dialog.modal-lg
    .modal-content

#modal-videos.modal.fade{:role => "dialog"}
  .modal-dialog.modal-lg
    .modal-content
      
:javascript
  var select_template = function(template) {
    $(".sample-template-text").val(template.title);
    $("#message_template_id").val(template.id);
    $('#modal-templates').modal('hide');
  }

  var select_video = function(video) {
    $(".sample-video-text").val(video.title);
    $("#message_video_id").val(video.id);
    $('#modal-videos').modal('hide');
  }

  var select_playlist = function(playlist) {
    $(".sample-playlist-text").val(playlist.title);
    $("#message_playlist_id").val(playlist.id);
    $('#modal-playlists').modal('hide');
  }

  var update_select_group = function() {
    var val = $('input[name="message[play]"]:checked').val();
    var show_list = (val == 'list');
    if (show_list){
      $('.playlists-group').show();
      $('.videos-group').hide();
    }else{
      $('.playlists-group').hide();
      $('.videos-group').show();
    }
  }

  function update_email_type(){
    if($('#message_email_type').is(":checked")){
      $('#send_at').show();
    }else{
      $('#send_at').hide();
    }
  }

  $('#message_email_type').on('click', function(){
    update_email_type();
  });

  update_email_type();


= content_for :javascript do
  :javascript
    $(function(){
      // Select play type
      $('input[name="message[play]"]').on('change', update_select_group);
      update_select_group();

      var remote_url = "#{contacts_messages_path + '?query=%QUERY' }";
      var contactList = new Bloodhound({
        datumTokenizer:  Bloodhound.tokenizers.obj.whitespace('value'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: remote_url
      });

      contactList.initialize();
      var tokenField = $('.typeahead').tokenfield({
        createTokensOnBlur: true,
        typeahead: {
          source: contactList.ttAdapter(),
          templates: {
            suggestion: function(token){
              return "" + token.fullname + " – " + token.value + "";
            }
          }
        }
      });
    });

app/views/messages/_message.html.haml
%tr
  %td
    = check_box_tag "messages[]", message.id
  %td
    - if message.deleted?
      = message.subject
    - else
      = link_to preview_message_path(message), title: 'Preview' do
        = message.subject
  %td
    %span{title: message.emails}
      = message.emails.split(',').first
      - if message.emails.split(',').count > 1
        = "(#{message.emails.split(',').count})"
  %td
    %span.glyphicon{class: message.status, title: message.status }
  %td
    - if message.sent? || message.delayed_email?
      - if message.send_at
        = message.send_at
      - else
        = message.updated_at

  %td.text-right
    .btn-group.actions
      - unless message.deleted?
        = link_to preview_message_path(message), title: 'Preview' do
          %span.glyphicon.glyphicon-eye-open
          - if message.draft?
            = link_to edit_message_path(message), title: 'Edit' do
              %span.glyphicon.glyphicon-pencil
          = link_to deliver_message_path(message), method: :put, title: 'Send' do
            %span.glyphicon.glyphicon-send
          = link_to clone_message_path(message), method: :put, title: 'Clone' do
            %span.glyphicon.glyphicon-hdd
          = link_to message_path(message), data: { confirm: 'Are you sure to delete?'}, method: :delete, title: 'Delete' do
            %span.glyphicon.glyphicon-trash

app/views/messages/_message_with_statistics.html.haml
- message.emails_to_a.each_with_index do |email, i|
  %tr
    %td
      - if i==0
        - if message.deleted?
          = message.subject
        - else
          = link_to preview_message_path(message), title: 'Preview' do
            = message.subject
    %td
      = email
    %td
      - if message.access_logs.by_email(email).count > 0
        = message.access_logs.by_email(email).first.accessed_at.utc.to_date
    %td
      - if message.access_logs.by_email(email).count > 0
        = message.access_logs.by_email(email).first.accessed_at.utc.to_s(:time)

    %td
      - if message.access_logs.by_email(email).count > 0
        = message.access_logs.by_email(email).first.accessed_at.to_date
    %td
      - if message.access_logs.by_email(email).count > 0
        = message.access_logs.by_email(email).first.accessed_at.to_s(:time)

    %td
      - if current_account.can_see_statistics?
        - if message.read_any?
          = link_to statistics_message_path(message), "data-target" => "#modal", "data-toggle" => "modal" do
            = pluralize(message.access_logs.by_email(email).count, 'time')
        - else
          = pluralize(message.access_logs.by_email(email).count, 'time')

%tr
  %td.bg-warning{:'colspan'=>'7'}

app/views/messages/_playlist.html.haml
%li
  = link_to "#", class: "sample-playlist", "data-playlist-title" => playlist.title, "data-playlist-id" => playlist.id do
    = image_tag playlist.screenshot, class: "playlist-thumb pull-left", style: "max-width: 100px;"
    %span.pull-left= playlist.title
    %span.clearfix

app/views/messages/_tabs.html.haml
= tabs_tag :open_tabs=>{ class: 'nav nav-tabs' } do |tab|
  = tab.all "All", messages_path
  = tab.sent "Sent", messages_path(status: 'sent')
  = tab.delayed "Scheduled", messages_path(status: 'delayed')
  = tab.draft "Draft", messages_path(status: 'draft')
  = tab.trash "Trash", messages_path(status: 'trash')
  - if current_account.can_see_statistics?
    = tab.statistics "Statistics", messages_path(statistics: true)

app/views/messages/_template.html.haml
%li
  = link_to "#", class: "sample-template", "data-template-title" => template.title, "data-template-id" => template.id do
    = image_tag template.preview_image.thumb.url, class: "template-thumb pull-left", style: "max-width: 100px;"
    %span.pull-left= template.title
    %span.clearfix

app/views/messages/_video.html.erb
<li>
<%= link_to "#", class: "sample-video", "data-video-title" => video.title, "data-video-id" => video.id do %>
  <%= image_tag video.screenshot, class: "video-thumb pull-left"  %>
  <span class="pull-left"><%= video.title %></span>
  <span class="clearfix"></span>
<% end %>
</li>

app/views/messages/edit.html.haml
#messages
  .box-header
    %h2 
      %span.glyphicon.glyphicon-envelope
      Edit videomail
  .box-body
    = render 'form'

app/views/messages/index.html.haml
#messages
  .box-header
    = link_to "<span class='glyphicon glyphicon-envelope'></span> New videomail".html_safe, new_message_path, class: "btn btn-primary pull-right"
    %h2
      %span.glyphicon.glyphicon-envelope
      Videomails
  .box-body
    = render 'messages/tabs'
    = form_tag '#', method: :put do
      %table.table
        %tbody
          = render @messages

      - if @messages.count > 0
        .actions
          - if params[:status] == 'trash'
            = link_to 'Delete Permanantly', '#', class: 'btn btn-danger', id: 'btn-delete-selected', disabled: true, onclick: "really_delete_messages();"
            = link_to 'Restore Selected', '#', class: 'btn btn-info', id: 'btn-restore-selected',  disabled: true, onclick: "restore_messages();"
          - else
            = link_to 'Delete Selected', '#', class: 'btn btn-danger', id: 'btn-delete-selected', disabled: true, onclick: "delete_messages();"
      - else
        %p.alert.alert-info
          There is no messages.
    = paginate(@messages)

:javascript
  function delete_messages(){
    $('form').attr('action', "#{destroy_multiple_messages_path}");
    if (confirm('Are you sure to delete?')){
      $('form').submit();
    }
  }

  function really_delete_messages(){
    $('form').attr('action', "#{really_destroy_multiple_messages_path}");
    if (confirm('Are you sure to delete?')){
      $('form').submit();
    }
  }

  function restore_messages(){
    $('form').attr('action', "#{restore_multiple_messages_path}");
    if (confirm('Are you sure to restore?')){
      $('form').submit();
    }
  }

  function update_button_statuses(){
    if($('input:checked').length<1){
      $('.actions .btn').attr('disabled', true);
    }else{
      $('.actions .btn').attr('disabled', false);
    }
  }

  $('input').on('click', function(){
    update_button_statuses();
  });

  update_button_statuses();

app/views/messages/index_with_statistics.html.haml
#messages
  .box-header
    = link_to "<span class='glyphicon glyphicon-envelope'></span> New videomail".html_safe, new_message_path, class: "btn btn-primary pull-right"
    %h2
      %span.glyphicon.glyphicon-envelope
      Videomails
  .box-body
    = render 'messages/tabs'
    .table-responsive
      %table.table.table-statistics
        %tbody
          %thead
            %th Title
            %th Email
            %th{title: 'Last read date'} Read date (System)
            %th{title: 'Last read time'} Read time (System)
            %th{title: 'Last read date'} Read date (Local)
            %th{title: 'Last read time'} Read time (Local)
            %th Read
          - @messages.each do |message|
            = render 'message_with_statistics', message: message

      = paginate(@messages)

app/views/messages/new.html.haml
#messages
  .box-header
    %h2
      %span.glyphicon.glyphicon-envelope
      New videomail
  .box-body
    = render 'form'

app/views/messages/preview.html.haml
- if !@playlist.blank?
  = image_tag @playlist.screenshot, class: 'img-responsive'
  .play-icon-wrapper
    = image_tag 'play_icon.png', class: 'play-icon'
- if !@video.blank?
  = image_tag @video.screenshot, class: 'img-responsive'
  .play-icon-wrapper
    = image_tag 'play_icon.png', class: 'play-icon'
  - if @message.downloadable
    %p.download.text-center
      = link_to "Download - #{@video.title}", download_video_path(@video, token: params[:token])

app/views/messages/statistics.html.haml
.modal-header
  %h3 Statistics
.modal-body.statistics
  - @message.emails_to_a.each do |email|
    %h4
      = email
      have read
      = pluralize(@message.access_logs.by_email(email).count, 'time')

    %ul
      - @message.access_logs.by_email(email).each do |log|
        %li
          = "#{log.accessed_at}"
      
.modal-footer
  %button.btn.btn-default.pull-right{"data-dismiss" => "modal", :type => "button"} Close