config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :accounts, controllers: { registrations: 'registrations' }
  devise_scope :account do
    get '/p/:referrer_code', to: 'registrations#promolink', as: 'promolink'
    match '/auth/:provider/callback', to: 'registrations#omniauth', via: [:get, :post]
    get '/auth/failure', to: redirect('/')
  end

  # Panda Routes
  scope default_format: :json do
    post '/panda/authorize_upload', to: 'panda#authorize_upload'
    post '/panda/notifications', to: 'panda#notifications'
  end

  resources :videos do
    get :preview, on: :member
    put :refresh, on: :member
    get :download, on: :member
    get :selection, on: :collection
  end

  resources :messages do
    member do
      put :deliver
      put :clone
      get :preview
      get :statistics
    end
    
    collection do
      get :contacts
      get :statistics
      put :destroy_multiple
      put :restore_multiple
      put :really_destroy_multiple
    end
  end

  resources :templates, only: [:index, :show] do
    member do
      get :preview
      delete :remove
    end
    collection do
      get :selection
      get :available
    end
  end

  resources :products, only: [:index, :show] do
    put :add_to_user, on: :member
  end

  resources :orders, only: [:index, :new, :create]

  resources :pages, only:[] do
    get :termsofuse, on: :collection
    get :imprint, on: :collection
    get :contact, on: :collection 
  end

  resources :playlists do
    put :add_video, on: :member
    put :remove_video, on: :member
    get :selection, on: :collection
  end

  get '/record', to: 'video_recorder#record'
  get '/avc_settings', to: 'video_recorder#avc_settings'
  post '/jpg_encoder_download', to: 'video_recorder#jpg_encoder_download'

  namespace :admin do
    resources :videos do
      get :preview, on: :member
      put :refresh, on: :member
    end

    resources :templates
    resources :categories
    resources :settings

    resources :products do
      put :add_category, on: :member
      put :remove_category, on: :member
    end

    resources :packages do
      get :manage_templates, on: :member
      put :add_template, on: :member
      put :remove_template, on: :member
    end

    root 'templates#index'
  end

  root 'videos#index'
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :account, counter_cache: true
  has_many :messages, dependent: :destroy
  has_and_belongs_to_many :playlists

  validates_presence_of :panda_video_id, if: 'stream_name.blank?'
  validates_presence_of :stream_name, if: 'panda_video_id.blank?'
  validates :title, :presence => true, :length => { :minimum => 5 }, :on => [ :update ], if: 'encoded'

  scope :most_recent, -> { order('created_at DESC') }
  scope :encoded, -> { where(encoded: true) }

  after_save :encode_video, if: 'panda_video_id.blank?'
  before_save :entitle

  PANDA_PROFILE_NAMES = %w(h264 ogg)

  def formatted_title
    return self.title if !self.title.blank?
    return 'Untitled'
  end

  def status
    return 'encoded' if self.encoded
    return 'in encoding'
  end

  def panda_video
    @panda_video ||= Panda::Video.find(self.panda_video_id)
  end

  def encodings
    @encodings ||= self.panda_video.encodings
  end

  def screenshots
    if self.panda_video_id
      @screenshots ||= self.encodings.first.screenshots
    else
      []
    end
  end

  def stream_name_url
     File.join(Rails.application.secrets[:hdfvr]['content_path'], self.stream_name) + '.flv'
  end

  def download_url
    s3 = AWS::S3.new
    s3_videos_bucket = Panda::Cloud.find(self.panda_video.cloud_id).s3_videos_bucket
    bucket = s3.buckets[s3_videos_bucket]
    object = bucket.objects[self.panda_video.encodings.last.files.first]
    object.url_for(:get, { 
      expires: 60.minutes,
      response_content_disposition: 'attachment;'
    }).to_s
  end

  def cache_panda_attrs(encoding_name)
    encoding = self.encodings[encoding_name]
    self.screenshot ||= encoding.screenshots.first
    self.height ||= encoding.height
    self.width ||= encoding.width
    self.encoded = true
    self.file_size ||= self.panda_video.file_size
    self.duration ||= self.panda_video.duration
    self.send("#{encoding_name}_url=", encoding.url)
  end

  def refresh
    if panda_video_id.blank?
      self.encode_video
    else
      self.encodings.each do |encoding|
        if encoding.status == 'success'
          self.cache_panda_attrs(encoding.profile_name)
          self.save(validate: false)
        end
      end
    end
  end

  def self.accept_upload?(file_name)
    mime_type = Rack::Mime.mime_type(File.extname(file_name))
    mime_type.start_with? 'video'
  end

  def is_accessible?(account, token)
    if self.account == account
      # Owner
      true
    else
      messages.by_token(token).exists?
    end
  end

  def encode_video
    EncodeVideo.perform_async(self.id)
  end

  private

  def entitle
    self.title ||= "Untitled #{self.account.videos.count}"
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  def index
    @videos = current_account.videos.most_recent
  end

  def show
    @video = Video.find(params[:id])
    if @video.panda_video_id
      @h264_encoding = @video.encodings['h264']
      @ogg_encoding = @video.encodings['ogg']
    end

    render :preview, layout: false
  end

  def preview
    @video = Video.find(params[:id])
    if @video.panda_video_id
      @h264_encoding = @video.encodings['h264']
      @ogg_encoding = @video.encodings['ogg']
    end
  end

  def new
    @video = current_account.videos.build
  end

  def create
    @video = current_account.videos.build(video_params)
    if @video.save
      flash[:success] = 'Video successfully created'
      redirect_to edit_admin_video_path(@video)
    else
      flash.now[:danger] = @video.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @video = current_account.videos.find(params[:id])
    @screenshots = @video.screenshots
  end

  def update
    @video = current_account.videos.find(params[:id])
    if @video.update_attributes(video_params)
      flash[:success] = 'Video successfully updated'
      redirect_to admin_videos_path
    else
      flash.now[:danger] = @video.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @video = current_account.videos.find(params[:id])
    @video.destroy
    respond_to do |format|
      format.js
      format.html{ redirect_to admin_videos_path }
    end
  end

  def refresh
    @video = current_account.videos.find(params[:id])
    @video.refresh

    redirect_to edit_admin_video_path(@video)
  end

  private

    def video_params
      params.require(:video).permit(:panda_video_id, :title, :screenshot, :stream_name)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :authenticate_account!, only: [:show, :download]
  before_filter :restrict_access_by_token, only: [:show, :download] 
  before_filter :set_video, only: [:preview, :edit, :update, :refresh, :destroy]

  def index
    @videos = current_account.videos.most_recent.page(params[:page])
  end

  def show
    if @video.encoded
      @h264_encoding = @video.encodings['h264']
      @ogg_encoding = @video.encodings['ogg']
    end

    @message = @video.messages.by_token(params[:token]).first
    if !@message.blank?
      @template = @message.template
      @message.read_by!(params[:email]) if !params[:email].blank?
      render 'show', layout:'email'
    end
  end

  def download
    redirect_to @video.download_url if @video.encoded
  end

  def preview
    if @video.encoded
      @h264_encoding = @video.encodings['h264']
      @ogg_encoding = @video.encodings['ogg']
    end
  end

  def new
    @video = current_account.videos.build
  end

  def create
    @video = current_account.videos.build(video_params)
    if @video.save
      flash[:success] = 'Video created successfully'
      redirect_to edit_video_path(@video)
    else
      flash.now[:danger] = @video.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @screenshots = @video.screenshots
  end

  def update
    @video = current_account.videos.find(params[:id])
    if @video.update_attributes(video_params)
      flash[:success] = 'Video updated successfully'
      redirect_to videos_path
    else
      flash.now[:danger] = @video.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @video.messages.blank?
      @video.destroy
      flash[:success] = 'Video destroyed successfully'
    else
      flash[:alert] = "Sorry, couldn't destroy video, because its in use"
    end
    redirect_to videos_path
  end

  def refresh
    @video.refresh

    redirect_to edit_admin_video_path(@video)
  end

  def selection
    index
    render 'selection', layout: false
  end

  private

  def video_params
    params.require(:video).permit(:panda_video_id, :title, :screenshot, :stream_name)
  end

  def set_video
    @video = current_account.videos.find(params[:id])
  end

  def restrict_access_by_token
    @video = Video.find(params[:id])
    unless @video.is_accessible?(current_account, params[:token])
      flash[:alert] = 'Access denied'
      if current_account
        redirect_to root_path
      else
        redirect_to new_account_session_path
      end
    end
  end
end

app/views/videos/_selection.html.haml
- @videos.each_with_index do |video, i|
  .col-md-3.template
    .previewimg
      - if video.screenshot
        = image_tag video.screenshot
      - else
        = image_tag '140x140-default.png'
    .template-title
      %h4= truncate(video.title, length: 20)
    .row
      .template-meta.col-md-12
        = link_to "#", class: 'btn btn-primary', "onclick"=>"select_video(#{video.to_json});" do
          %span.glyphicon.glyphicon-eye-open
          %span Select

  - if (i+1) % 4 == 0
    .clearfix

app/views/videos/_video.html.haml
%tr
  %td.prelative
    %p
      = link_to preview_video_path(video), title: "Preview" do
        - if video.encoded
          = image_tag video.screenshot, style: "max-height: 100px;"
        - else
          = image_tag "encoding.jpg", class: 'img-responsive', style: "max-height: 100px"
      
      - if !video.encoded?
        .text-center.pabsolute.video-refresh
          = link_to refresh_video_path(video), class: 'btn btn-info', method: :put do
            %span.glyphicon.glyphicon-refresh

  %td= link_to truncate(video.formatted_title, length: 25), preview_video_path(video), title: "Preview", target: "_blank"
  %td= video_status(video)
  %td= "#{video.width}x#{video.height}"
  %td= video.created_at
  %td= number_to_human_size(video.file_size)
  %td= video_duration_human(video.duration)
  %td
    .btn-group.actions
      = link_to preview_video_path(video), title: "Preview" do
        %span.glyphicon.glyphicon-eye-open
      = link_to edit_video_path(video) do
        %span.glyphicon.glyphicon-pencil
      = link_to video_path(video), method: :delete, data:{ confirm: "Are you sure to delete?" } do
        %span.glyphicon.glyphicon-trash
      = link_to new_message_path(video_id: video.id), title: "Create message"  do
        %span.glyphicon.glyphicon-envelope

app/views/videos/edit.html.haml
.box-header
  %h2 Edit Video
.box-body
  = bootstrap_form_for(@video) do |f|
    = f.text_field :title, onfocus: 'this.select();'

    = f.form_group do
      %h5
        Preview Image
        %span.small
          (choose by clicking on it)
      - if !params[:select_thumbanil].blank? or @video.screenshot.blank?
        .row
          = collection_radio_buttons(:video, :screenshot, @video.screenshots, :to_s, :to_s) do |b|
            .col-xs-6.col-md-4
              .radio.select
                = b.label( class: 'no-padding' ) do
                  = b.radio_button( class: 'hide' )
                  = image_tag(b.object, class: 'img-responsive img-rounded')
      - else
        = image_tag(@video.screenshot, class: 'img-responsive img-rounded')
        %br/
        = link_to "Choose from screenshots", edit_video_path(@video, select_thumbanil: true), class: 'btn btn-info'

    = f.form_group do
      = f.label "Status: "
      = @video.status

    = f.form_group do
      = f.submit "Save", class: "btn btn-primary"
      - if !@video.encoded
        = link_to "Refresh", refresh_video_path(@video), class: 'btn btn-info', method: :put

app/views/videos/index.html.haml
#video-overview
  .box-header
    //= link_to "<span class='glyphicon glyphicon-film'></span> New Video".html_safe, new_video_path, class: 'btn btn-primary pull-right'
    %h2
      %span.glyphicon.glyphicon-film
      Videos

  .box-body
    .table-responsive
      %table.table.table-condensed.table-striped
        %thead
          %tr
            %th
            %th Title
            %th Status
            %th Dimensions
            %th Uploaded
            %th Size
            %th Duration
            %th
        %tbody
          = render @videos

app/views/videos/new.html.erb
<div class="box-header">
  <h2>New Video</h2>
</div>  
<div class="box-body">
  <%= form_for @video, html: { role: "form" } do |f| %>
    <%= f.hidden_field :panda_video_id %>

    <div id="upload-error" class="alert flash alert-danger" style="display: none;">
      Not a video file
    </div>

    <div class="progress progress-striped active">
      <div id="progress-bar" class="progress-bar progress-bar-success"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
        <span class="sr-only">0% Complete</span>
      </div>
    </div>

    <div class="form-group">
      <div id="browse" class="btn btn-primary">Choose file</div>
      <div id="cancel-btn" class="btn btn-danger">Cancel</div>
    </div>
  <% end %>

  <%= content_for :javascript do %>
    <script type="text/javascript">
      var currentFile = null;
      var uploadCancelled = false;
      var manualCancel = false;

      var upl = panda.uploader.init({
        'buttonId': 'browse',
        'onQueue': function(files) {
          $.each(files, function(i, file) {
            upl.setPayload(file, {'csrf': "<%= form_authenticity_token %>"});
          });
          currentFile = null;
          uploadCancelled = false;
          manualCancel = false;
          $('#upload-error').hide();
        },
        'onStart': function(file) {
          console.log("onStart");
          currentFile = file;
        },
        'onProgress': function(file, percent) {
          console.log("onProgress", percent, "%");
          $("#progress-bar").css("width", percent + "%");
        },
        'onSuccess': function(file, data) {
          console.log("onSuccess");
          $("#video_panda_video_id").val(data.id)
          currentFile = null;
        },
        'onError': function(file, message) {
          console.log("onError", message);
          currentFile = null;
        },
        'onCancel': function(file) {
          console.log("onCancel");
          uploadCancelled = true;

          if (!manualCancel) {
            $('#upload-error').show();
          }
        },
        'onComplete': function(){
          console.log("onComplete");
          if (!uploadCancelled) {
            $("#new_video").submit();
          }
          currentFile = null;
        }
      });

      $("#cancel-btn").click(function() {
        if (currentFile) {
          manualCancel = true;
          upl.cancel(currentFile);
          $("#progress-bar").css("width", "0%");
        }
      });

      $('.panda-uploader').attr('accept', 'video/*');
    </script>
  <% end %>
</div>  

app/views/videos/preview.html.haml
.box-header
  %h2= @video.title
.box-body.text-center
  - if @video.encoded
    %video#movie{:controls => '', :height => 'auto', :poster => @video.screenshots.first, :preload => 'none', :width => '600'}
      %source{:src => @h264_encoding.url, :type => 'video/mp4'}
      %source{:src => @ogg_encoding.url, :type => 'video/ogg'}
  - else
    = image_tag 'encoding.jpg', class: 'img-responsive', style: 'max-height: 200px'

  .footerline
  .text-right
    = link_to 'Back', :back, class: 'btn btn-back btn-info'
    - if @video.encoded
      = link_to 'Send this as videomail now', new_message_path(video_id: @video.id), class: 'btn btn-primary'
    - else
      = link_to 'Refresh', refresh_video_path(@video), class: 'btn btn-info', method: :put

app/views/videos/selection.html.haml
.box-header
  %h2.pull-left
    %span.glyphicon.glyphicon-th
    Your videos

  %button.btn.btn-default.pull-right{"data-dismiss" => "modal", :type => "button"} X
.box-body
  .row
    #videos
      = render 'selection'
  #paginator
    = paginate @videos, :remote => true

app/views/videos/selection.js.haml
$('#modal-videos #videos').html('#{escape_javascript render 'selection'}');
$('#modal-videos #paginator').html('#{escape_javascript(paginate(@videos, :remote => true).to_s)}');

app/views/videos/show.html.haml
%video#movie{:controls => "", :height => "auto", :poster => @video.screenshots.first, :preload => "none", :width => "100%", :autoplay=> true}
  %source{:src => @video.h264_url, :type => "video/mp4"}
  %source{:src => @video.ogg_url, :type => "video/ogg"}

- if @message.downloadable
  %p.download.text-center
    = link_to "Download - #{@video.title}", download_video_path(@video, token: params[:token])