config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :accounts, controllers: { registrations: 'registrations' }
  devise_scope :account do
    get '/p/:referrer_code', to: 'registrations#promolink', as: 'promolink'
    match '/auth/:provider/callback', to: 'registrations#omniauth', via: [:get, :post]
    get '/auth/failure', to: redirect('/')
  end

  # Panda Routes
  scope default_format: :json do
    post '/panda/authorize_upload', to: 'panda#authorize_upload'
    post '/panda/notifications', to: 'panda#notifications'
  end

  resources :videos do
    get :preview, on: :member
    put :refresh, on: :member
    get :download, on: :member
    get :selection, on: :collection
  end

  resources :messages do
    member do
      put :deliver
      put :clone
      get :preview
      get :statistics
    end
    
    collection do
      get :contacts
      get :statistics
      put :destroy_multiple
      put :restore_multiple
      put :really_destroy_multiple
    end
  end

  resources :templates, only: [:index, :show] do
    member do
      get :preview
      delete :remove
    end
    collection do
      get :selection
      get :available
    end
  end

  resources :products, only: [:index, :show] do
    put :add_to_user, on: :member
  end

  resources :orders, only: [:index, :new, :create]

  resources :pages, only:[] do
    get :termsofuse, on: :collection
    get :imprint, on: :collection
    get :contact, on: :collection 
  end

  resources :playlists do
    put :add_video, on: :member
    put :remove_video, on: :member
    get :selection, on: :collection
  end

  get '/record', to: 'video_recorder#record'
  get '/avc_settings', to: 'video_recorder#avc_settings'
  post '/jpg_encoder_download', to: 'video_recorder#jpg_encoder_download'

  namespace :admin do
    resources :videos do
      get :preview, on: :member
      put :refresh, on: :member
    end

    resources :templates
    resources :categories
    resources :settings

    resources :products do
      put :add_category, on: :member
      put :remove_category, on: :member
    end

    resources :packages do
      get :manage_templates, on: :member
      put :add_template, on: :member
      put :remove_template, on: :member
    end

    root 'templates#index'
  end

  root 'videos#index'
end

app/views/shared/_email_authorized.html.haml
- if !@message.video.blank?
  = render_template_content_for_video(@template, @message.video, 'text' => @message.text, 'link' => video_url(@message.video, token: @message.token), 'title' => @message.subject) do
    = yield

- if !@message.playlist.blank?
  = render_template_content_for_playlist(@template, @message.playlist, 'text' => @message.text, 'link' => playlist_url(@message.playlist, token: @message.token), 'title' => @message.subject) do
    = yield
    

app/views/shared/_email_unauthorized.html.haml
- if !@message.template.is_default?
  .template-header
    .container
      .row
        .col-md-12
          =link_to '/', class: 'template-logo' do
            =image_tag 'logo.png', height: 50

- if !@message.video.blank?
  = render_template_content_for_video(@template, @message.video, 'text' => @message.text, 'link' => video_url(@message.video, token: @message.token), 'title' => @message.subject) do
    = yield
      
- if !@message.playlist.blank?
  = render_template_content_for_playlist(@template, @message.playlist, 'text' => @message.text, 'link' => playlist_url(@message.playlist, token: @message.token), 'title' => @message.subject) do
    = yield

app/views/shared/_flashes.html.erb
<% flash.each do |name, msg| %>
  <div class="alert flash alert-<%= name %> fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <%= msg %>
  </div>
<% end %>
  

app/views/shared/_footer.html.haml
%footer
  %ul.footer-nav
    %li.mr2 © 2014 All Rights Reserved, BONOFA AG
    %li
      = link_to "Terms of use", main_app.termsofuse_pages_path
    %li
      = link_to "Imprint", main_app.imprint_pages_path
    %li
      = link_to "Contact", main_app.contact_pages_path

app/views/shared/_header.html.haml
- if account_signed_in?
  = render 'shared/header_authorized'
- else
  = render 'shared/header_unauthorized'

app/views/shared/_header_admin.html.haml
.navbar.navbar-fixed-top.navbar-inverse{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        = image_tag 'logo.png', class: 'img-responsive', width: '150'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{:class => filter_links_class(/\/templates/)}
          = link_to "Templates", admin_templates_path
        %li{:class => filter_links_class(/\/videos/)}
          = link_to "Videos", admin_videos_path
        %li{:class => filter_links_class(/\/packages/)}
          = link_to "Packages", admin_packages_path
        %li{:class => filter_links_class(/\/categories/)}
          = link_to "Categories", admin_categories_path
        %li{:class => filter_links_class(/\/products/)}
          = link_to "Products", admin_products_path
        %li{:class => filter_links_class(/\/settings/)}
          = link_to "Settings", admin_settings_path

      %p.navbar-text.navbar-right
        = link_to "Sign out", destroy_account_session_path, :method => 'delete'
      %p.navbar-text.navbar-right
        Signed in as
        %a.navbar-link{:href => "#"}
          = current_account.full_name

app/views/shared/_header_authorized.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        = image_tag('logo_intern.png')

    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li{:class => filter_links_class(/\/videos/, main_app.root_url)}
          = link_to "Videos", main_app.videos_path
        - if current_account.try :can_use_video_playlist?
          %li{:class => filter_links_class(/\/playlist/)}
            = link_to "Playlists", main_app.playlists_path
        %li{:class => filter_links_class(/\/messages/)}
          = link_to "Videomails", main_app.messages_path
        %li{:class => filter_links_class(/\/templates/)}
          = link_to "Templates", main_app.templates_path
        -# %li.disabled{:class => filter_links_class(/\/addressbook/)}
          -# = link_to "Addressbook", "javascript:void(0)", title: "Coming soon..."
        -# %li.disabled{:class => filter_links_class(/\/payments/)}
          -# = link_to "Payments", "javascript:void(0)", title: "Coming soon..."
        %li.dropdown
          %a#profiletoggle{:href => "#"}
            %span.icon-user
            %span.toggle-title Profile
            %span.toggle-icon.glyphicon.glyphicon-circle-arrow-down
        %li
          = link_to "<span class='glyphicon glyphicon-off'></span>".html_safe, main_app.destroy_account_session_path, :method => 'delete', :title => 'Logout'
    / /.navbar-collapse
  / /.container-fluid
/ Profile row
#profile.container-fluid
  .col-xs-12.col-sm-6
    / profileimage
    .col-xs-5.col-sm-5.col-md-5.col-lg-4
      .profileimg
        = image_tag('nouserimage.jpg', class: 'img-responsive img-circle')
        // %a{:alt => "change profile image", :href => "#"}
        //  %span.glyphicon.glyphicon-picture
        //  %span.txt Change Image
        .clearfix
    / Welcometext
    .col-xs-7.col-sm-6.col-md-6.col-lg-8.welcome
      %h1.bob
        %span.small Welcome
        = succeed "#{current_account.first_name}," do
          %br/
        = current_account.last_name
        -#%p Welcome text... news, features etc. ein netter kleiner Wohlfühltext, eventuell textlich andere Produkte anteasern... haben sie schon dies und das probiert?

  / current package, settinglinks
  .col-xs-12.col-sm-6.bgcolor.profilesettings
    .actions
      .col-xs-6.bor
        %a{:href => edit_account_registration_path}
          %span.glyphicon.glyphicon-user
          Profile Setting
      .col-xs-6
        %a{:href => orders_path}
          %span.glyphicon.glyphicon-credit-card
          Payment
    %table.table.table-condensed
      %tr
        %td Company:
        %td - none -
      %tr
        %td Account:
        %td
          = current_account.current_plan.name
          user
      %tr
        %td e-Mail:
        %td= current_account.email
      %tr
        %td
          %strong Your promolink:
        %td
          - if current_account.promotion_code.present?
            = promolink_url(referrer_code: current_account.promotion_code)
          - else
            \-
/ Profile End

-#.navbar.navbar-fixed-top.navbar-inverse{:role => "navigation"}
-#  .container
-#    .navbar-header
-#      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
-#        %span.sr-only Toggle navigation
-#        %span.icon-bar
-#        %span.icon-bar
-#        %span.icon-bar
-#      %a.navbar-brand{:href => "/"}
-#        = image_tag 'logo.png'
-#        %span BETA
-#    - if account_signed_in?
-#      .collapse.navbar-collapse
-#        %ul.nav.navbar-nav.navbar-right
-#          %li{:class => filter_links_class(/\/videos/, main_app.root_url)}
-#            = link_to "Videos", main_app.videos_path
-#          %li{:class => filter_links_class(/\/playlist/)}
-#            = link_to "Playlists", main_app.playlists_path
-#          %li{:class => filter_links_class(/\/messages/)}
-#            = link_to "Messages", main_app.messages_path
-#          %li.disabled{:class => filter_links_class(/\/addressbook/)}
-#            = link_to "Addressbook", "javascript:void(0)", title: "Coming soon..."
-#          %li{:class => filter_links_class(/\/templates/)}
-#            = link_to "Templates", main_app.templates_path
-#          %li{:class => filter_links_class(/\/products/)}
-#            = link_to "Buy", main_app.products_path
-#          %li.disabled{:class => filter_links_class(/\/payments/)}
-#            = link_to "Payments", "javascript:void(0)", title: "Coming soon..."
-#          %li
-#            = link_to "<span class='glyphicon glyphicon-log-out'></span>".html_safe, main_app.destroy_account_session_path, :method => 'delete', :title => 'Logout'

app/views/shared/_header_unauthorized.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        = image_tag('logo_intern.png')

    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li{:class => filter_links_class(/\/videos/, main_app.root_url)}
          = link_to "Videos", main_app.videos_path
        - if current_account.try :can_use_video_playlist?
          %li{:class => filter_links_class(/\/playlist/)}
            = link_to "Playlists", main_app.playlists_path
        %li{:class => filter_links_class(/\/messages/)}
          = link_to "Videomails", main_app.messages_path
        %li
          = link_to "<span class='glyphicon glyphicon-log-in'></span>".html_safe, main_app.new_account_session_path, :title => 'Login'
    / /.navbar-collapse
  / /.container-fluid

app/views/shared/_meta_tags.html.haml
%meta{ :charset => 'utf-8' }
%meta{ :content => 'IE=edge', 'http-equiv' => 'X-UA-Compatible' }
%meta{ :content => 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no', :name => 'viewport' }
%meta{ :content => '', :name => 'description' }
%meta{ :content => '', :name => 'author' }
%meta{:content => "79ec32681775c1b2-b75623a97a67ca61-g6810210fa972dcaf-12", :name => "google-translate-customization"}/

%link{ :rel => 'apple-touch-icon-precomposed', :href => '/assets/apple-touch-icon-57x57-precomposed.png',   :sizes => '57x57' }
%link{ :rel => 'apple-touch-icon-precomposed', :href => '/assets/apple-touch-icon-72x72-precomposed.png',   :sizes => '72x72' }
%link{ :rel => 'apple-touch-icon-precomposed', :href => '/assets/apple-touch-icon-76x76-precomposed.png',   :sizes => '76x76' }
%link{ :rel => 'apple-touch-icon-precomposed', :href => '/assets/apple-touch-icon-114x114-precomposed.png', :sizes => '114x114' }
%link{ :rel => 'apple-touch-icon-precomposed', :href => '/assets/apple-touch-icon-120x120-precomposed.png', :sizes => '120x120' }
%link{ :rel => 'apple-touch-icon-precomposed', :href => '/assets/apple-touch-icon-144x144-precomposed.png', :sizes => '144x144' }
%link{ :rel => 'apple-touch-icon-precomposed', :href => '/assets/apple-touch-icon-152x152-precomposed.png', :sizes => '152x152' }
%link{ :rel => 'apple-touch-icon-precomposed', :href => '/assets/apple-touch-icon-precomposed.png' }

app/views/shared/_sidebar.html.haml
#sidebar.row.sidebar-offcanvas{:role => "navigation"}
  .col-xs-12.col-sm-12
    = link_to "<span class='glyphicon glyphicon-film'></span>Record a new video".html_safe, main_app.record_path, :class => 'btn btn-primary recordvideo'
  .col-xs-12.col-sm-12
    = link_to "<span class='glyphicon glyphicon-cloud-upload'></span>Upload your video".html_safe, main_app.new_video_path, :class => 'btn btn-primary uploadvideo'
  .col-xs-12.col-sm-12
    = link_to "<span class='glyphicon glyphicon-envelope'></span>Create videomail".html_safe, new_message_path, :class => "btn btn-primary newmessage"

app/views/shared/_translate.html.haml
#google_translate_element
  :javascript
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false}, 'google_translate_element');
    }
  %script{:src => "//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit", :type => "text/javascript"}