config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :accounts, controllers: { registrations: 'registrations' }
  devise_scope :account do
    get '/p/:referrer_code', to: 'registrations#promolink', as: 'promolink'
    match '/auth/:provider/callback', to: 'registrations#omniauth', via: [:get, :post]
    get '/auth/failure', to: redirect('/')
  end

  # Panda Routes
  scope default_format: :json do
    post '/panda/authorize_upload', to: 'panda#authorize_upload'
    post '/panda/notifications', to: 'panda#notifications'
  end

  resources :videos do
    get :preview, on: :member
    put :refresh, on: :member
    get :download, on: :member
    get :selection, on: :collection
  end

  resources :messages do
    member do
      put :deliver
      put :clone
      get :preview
      get :statistics
    end
    
    collection do
      get :contacts
      get :statistics
      put :destroy_multiple
      put :restore_multiple
      put :really_destroy_multiple
    end
  end

  resources :templates, only: [:index, :show] do
    member do
      get :preview
      delete :remove
    end
    collection do
      get :selection
      get :available
    end
  end

  resources :products, only: [:index, :show] do
    put :add_to_user, on: :member
  end

  resources :orders, only: [:index, :new, :create]

  resources :pages, only:[] do
    get :termsofuse, on: :collection
    get :imprint, on: :collection
    get :contact, on: :collection 
  end

  resources :playlists do
    put :add_video, on: :member
    put :remove_video, on: :member
    get :selection, on: :collection
  end

  get '/record', to: 'video_recorder#record'
  get '/avc_settings', to: 'video_recorder#avc_settings'
  post '/jpg_encoder_download', to: 'video_recorder#jpg_encoder_download'

  namespace :admin do
    resources :videos do
      get :preview, on: :member
      put :refresh, on: :member
    end

    resources :templates
    resources :categories
    resources :settings

    resources :products do
      put :add_category, on: :member
      put :remove_category, on: :member
    end

    resources :packages do
      get :manage_templates, on: :member
      put :add_template, on: :member
      put :remove_template, on: :member
    end

    root 'templates#index'
  end

  root 'videos#index'
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :account

  has_and_belongs_to_many :videos
  has_many :messages, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :outro_text, length: { maximum: 255 }
  validates :description, length: { maximum: 255 }

  def screenshot
    self.videos.first.try(:screenshot)
  end

  def is_accessible?(account, token)
    if self.account == account
      # Owner
      true
    else
      messages.by_token(token).exists?
    end
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  skip_before_action :authenticate_account!, only: [:show]
  before_filter :set_playlist, only: [:edit, :update, :destroy, :add_video, :remove_video]
  before_filter :set_videos, only: [:edit, :update]

  before_filter except: :show do
    unless current_account.can_use_video_playlist?
      redirect_to root_path, notice: 'Upgrade your plan to use video playlists'
      false
    end
  end

  def index
    @playlists = current_account.playlists.page(params[:page])
  end

  def show
    @playlist = Playlist.find(params[:id])
    @playlist.videos ||= []

    # Token access
    unless @playlist.is_accessible?(current_account, params[:token])
      flash[:alert] = 'Access denied'

      if current_account
        redirect_to root_path
      else
        redirect_to new_account_session_path
      end
    else
      @message = @playlist.messages.by_token(params[:token]).first
      if !@message.blank?
        @template = @message.template
        @message.read_by!(params[:email]) if !params[:email].blank?
        render 'show', layout:'email'
      end
    end
  end

  def new
    @playlist = current_account.playlists.build
  end

  def create
    @playlist = current_account.playlists.build(playlist_params)
    if @playlist.save
      redirect_to edit_playlist_path(@playlist), flash: { success: 'Playlist created successfully' }
    else
      flash.now[:danger] = @playlist.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @playlist = current_account.playlists.find(params[:id])
  end

  def update
    @playlist = current_account.playlists.find(params[:id])

    if @playlist.update_attributes(playlist_params)
      redirect_to edit_playlist_path(@playlist), flash: { success: 'Playlist updated successfully' }
    else
      flash.now[:danger] = @playlist.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @playlist.destroy
    redirect_to playlists_path
  end

  def add_video
    @video = current_account.videos.find(params[:video_id])
    @playlist.videos ||= []
    @playlist.videos << @video if !@playlist.videos.include?(@video)
    @playlist.save

    redirect_to edit_playlist_path(@playlist)
  end

  def remove_video
    @video = @playlist.videos.find(params[:video_id])
    @playlist.videos.destroy(@video)
    redirect_to edit_playlist_path(@playlist)
  end

  def selection
    index
    render 'selection', layout: false
  end

  private

  def playlist_params
    params.require(:playlist).permit(:title, :description, :outro_text)
  end

  def set_playlist
    @playlist = current_account.playlists.find(params[:id])
    @playlist.videos ||= []
  end

  def set_videos
    ids_to_exclude = @playlist.videos.map(&:id)
    @videos = current_account.videos.where.not(id: ids_to_exclude).page(params[:page])
  end
end

app/views/playlists/_form.html.haml
#new-playlist
  = bootstrap_form_for(@playlist, layout: :vertical) do |f|
    = f.text_field :title

    - if !@playlist.new_record?
      = f.form_group do
        .playlist-checked
          %h5 Playlist:
          - if @playlist.videos.count > 0
            .row
              - @playlist.videos.each do |video|
                = render 'video', video: video
              .col-sm-3.playlist-outro.nopaddingleft
                = f.text_area :outro_text, class: 'form-control', rows: 6, placeholder: 'Your outro message', hide_label: true

          - else
            %p.text-info.playlist-example
              There is no video in this playlist, Please add some videos in the below

      %hr

      = f.form_group do
        .playlist-videos
          %h5 Your Videos:
          - if !@playlist.new_record?
            - if @videos.count > 0
              .row
                - @videos.each do |video|
                  = render 'video', video: video
              = paginate @videos
            - else
              %p.text-info
                There is no available videos to add


    = f.form_group do
      = f.submit @playlist.persisted? ? 'Save' : 'Create', class: 'btn btn-primary'
      = link_to 'Save and close', playlists_path, class: 'btn btn-primary'

:javascript
  function setPlaylistHeight() {
    var outro = $('.playlist-outro textarea');
    var height = $('.playlist-video:first-child').outerHeight();
    var width = $('.playlist-video:first-child').outerWidth();

    outro.css({
      'height': height,
      'width': width
    })
  }
  setPlaylistHeight();

app/views/playlists/_playlist.html.haml
%tr
  %td= image_tag playlist.screenshot, style: "max-width: 100px;"
  %td=playlist.title
  %td=playlist.videos.count
  %td=playlist.created_at
  %td.text-right
    .btn-group.actions
      = link_to playlist_path(playlist), title: "Show" do
        %span.glyphicon.glyphicon-eye-open

      = link_to edit_playlist_path(playlist), title: "Edit" do
        %span.glyphicon.glyphicon-pencil
      
      = link_to playlist_path(playlist), data: { confirm: "Are you sure to delete?"}, method: :delete, title: "Delete" do
        %span.glyphicon.glyphicon-trash

      = link_to new_message_path(playlist_id: playlist.id), title: "Create message"  do
        %span.glyphicon.glyphicon-envelope

app/views/playlists/_selection.html.haml
- @playlists.each_with_index do |playlist, i|
  .col-md-3.template
    .previewimg
      - if playlist.screenshot
        = image_tag playlist.screenshot
      - else
        = image_tag '140x140-default.png'
    .template-title
      %h4= truncate(playlist.title, length: 20)
    .row
      .template-meta.col-md-12
        = link_to "#", class: 'btn btn-primary', "onclick"=>"select_playlist(#{playlist.to_json});" do
          %span.glyphicon.glyphicon-eye-open
          %span Select

  - if (i+1) % 4 == 0
    .clearfix

app/views/playlists/_video.html.haml
.col-sm-3.playlist-video
  %p
    = image_tag video.screenshot, style: "max-height: 100px;"
  %p
    = truncate(video.title, length: 25)
  %p
    - if @playlist.videos.include?(video)
      = link_to "Remove from playlist", remove_video_playlist_path(@playlist, video_id: video.id), data:{ method: :put, confirm: "Are you sure to remove?" }, class: 'btn btn-danger'
    - else
      = link_to "Add to playlist", add_video_playlist_path(@playlist, video_id: video.id), data:{ method: :put }, class: 'btn btn-primary'

app/views/playlists/edit.html.haml
.box-header
  %h2 
    %span.glyphicon.glyphicon-list-alt
    Edit playlist structure
.box-body
  = render 'form'

app/views/playlists/index.html.haml
.box-header
  = link_to "<span class='glyphicon glyphicon-list-alt'></span> New Playlist".html_safe, new_playlist_path, class: "btn btn-primary pull-right"
  %h2 
    %span.glyphicon.glyphicon-list-alt
    Playlist(s)
.box-body  
  .table-responsive
    %table.table.table-condensed.table-striped
      %thead
        %th
        %th Title
        %th Videos
        %th Created at
        %th
      = render @playlists

  = paginate(@playlists)

app/views/playlists/new.html.haml
.box-header
  %h2 
    %span.glyphicon.glyphicon-list-alt
    New playlist
.box-body
  = render 'form'

app/views/playlists/selection.html.haml
.box-header
  %h2.pull-left
    %span.glyphicon.glyphicon-th
    Your playlists

  %button.btn.btn-default.pull-right{"data-dismiss" => "modal", :type => "button"} X
.box-body
  .row
    #playlists
      = render 'selection'
  #paginator
    = paginate @playlists, :remote => true

app/views/playlists/selection.js.haml
$('#modal-playlists #playlists').html('#{escape_javascript render 'selection'}');
$('#modal-playlists #paginator').html('#{escape_javascript(paginate(@playlists, :remote => true).to_s)}');

app/views/playlists/show.html.haml
#player
  %video#movie{:controls => "", :height => "auto", :preload => "none", :width => "100%", :autoplay => true, :autobuffer => true}
    %source#h264{:type => "video/mp4"}
    %source#ogg{:type => "video/ogg"}

  - if !@playlist.outro_text.blank?
    .outro
      %div
        %span
          = @playlist.outro_text.html_safe

:javascript
  var videos = eval(#{@playlist.videos.to_json});
  var currentVideo = null;
  var videoPlayer = $('#movie');

  var initVideo = function(video){
    videoPlayer.attr('poster', video.screenshot);
    $('#h264').attr('src', video.h264_url);
    $('#ogg').attr('src', video.ogg_url);
    $('#movie').load();
    currentVideo = video;
  }

  var nextVideo = function(video){
    var index = (_.indexOf(videos, video) + 1) % videos.length
    return videos[index];
  }

  videoPlayer.bind('playing',function(){
    $('#player').removeClass('ended');
    $('#player').addClass('playing');
  });

  videoPlayer.bind('ended',function(){
    if (nextVideo(currentVideo) != videos[0]){
      initVideo(nextVideo(currentVideo));
    }

    if(currentVideo == videos[videos.length -1]){
      $('#player').removeClass('playing');
      $('#player').addClass('ended');
    }
  });

  initVideo(videos[0]);